floodrelief/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    path('', include('mainapp.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view()),
    path('api/1/rest-auth/', include('rest_auth.urls')),
    path('api/1/', include('mainapp.api_urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('ngo-volunteer/', views.NgoVolunteerView.as_view(), name='ngovolunteerview'),
    path('map-view/', views.MapView.as_view(), name='mapview'),
    path('request/', views.CreateRequest.as_view(), name='requestview'),
    # path('volunteer/', views.Maintenance.as_view(), name='registerview'),
    path('volunteer/', views.RegisterVolunteer.as_view(), name='registerview'),
    path('NGO/', views.RegisterNGO.as_view(), name='ngoregisterview'),
    path('NGO/download/', views.download_ngo_list, name='ngo_download_view'),
    path('requests/', views.request_list, name='requestlistview'),
    url(r'request_details/(?P<request_id>\d+)/$', views.request_details, name='requestdetailsview'),
    path('contactus/', views.districtmanager_list, name='contactus'),
    path('reg_success/', views.RegSuccess.as_view(), name='reg_successview'),
    path('req_sucess/', views.ReqSuccess.as_view(), name='req_sucessview'),
    path('district_needs/', views.DistNeeds.as_view(), name='distneedsview'),
    path('reg_contrib/', views.RegisterContributor.as_view(), name='reg_contribview'),
    path('contrib_success/', views.ContribSuccess.as_view(), name='contribsucessview'),
    path('disclaimer/', views.DisclaimerPage.as_view(), name='disclaimer'),
    path('ieee/', views.AboutIEEE.as_view(), name='aboutieee'),
    #path('data/' , views.mapdata , name="mapdata"),
    path('map/' , views.mapview , name="mapview"),
    path('dmodash/' , views.dmodash , name="DMODash"),
    path('dmoinfo/' , views.dmoinfo , name="DMOInfo" ),
    path('error/' , views.error , name="errorview" ),
    path('login/', auth_views.LoginView.as_view(template_name='mainapp/login.html'),name='user_login'),
    path('logout/', views.logout_view, name='user_logout'),
    path('relief_camps/', views.relief_camps, name='relief_camps'),
    path('relief_camps_list', views.relief_camps_list, name='relief_camps_list'),
    path('camp/<int:pk>/requirements/',views.CampRequirements.as_view(),name='camp_requirements'),
    path('camp/<int:pk>/details/',views.CampDetails.as_view(),name='camp_details'),
    path('camp/<int:camp_id>/add_person/', views.AddPerson.as_view(), name='add_person'),
    path('coordinator_home/', views.coordinator_home, name='coordinator_home'),
    path('find_people/', views.find_people, name='find_people'),
    path('announcements/', views.announcements, name="Announcements"),
    path('camp_requirements/', views.camp_requirements_list, name='camp_requirements_list')
]

mainapp/models.py
import os
import uuid
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User

districts = (
    ('alp','Alappuzha - ആലപ്പുഴ'),
    ('ekm','Ernakulam - എറണാകുളം'),
    ('idk','Idukki - ഇടുക്കി'),
    ('knr','Kannur - കണ്ണൂർ'),
    ('ksr','Kasaragod - കാസർഗോഡ്'),
    ('kol','Kollam - കൊല്ലം'),
    ('ktm','Kottayam - കോട്ടയം'),
    ('koz','Kozhikode - കോഴിക്കോട്'),
    ('mpm','Malappuram - മലപ്പുറം'),
    ('pkd','Palakkad - പാലക്കാട്'),
    ('ptm','Pathanamthitta - പത്തനംതിട്ട'),
    ('tvm','Thiruvananthapuram - തിരുവനന്തപുരം'),
    ('tcr','Thrissur - തൃശ്ശൂർ'),
    ('wnd','Wayanad - വയനാട്'),
)

status_types =(
    ('new', 'New'),
    ('pro', 'In progess'),
    ('sup', 'Supplied'),
)

contrib_status_types =(
    ('new', 'New'),
    ('ful', 'Fullfilled'),
)

vol_categories = (
    ('dcr', 'Doctor'),
    ('hsv', 'Health Services'),
    ('elw', 'Electrical Works'),
    ('mew', 'Mechanical Work'),
    ('cvw', 'Civil Work'),
    ('plw', 'Plumbing work'),
    ('vls', 'Vehicle Support'),
    ('ckg', 'Cooking'),
    ('rlo', 'Relief operation'),
    ('cln', 'Cleaning'),
    ('bot', 'Boat Service'),
    ('rck', 'Rock Climbing'),
    ('oth', 'Other')
)

gender =(
    (0,'Male'),
    (1,'Female'),
    (2,'Others')
)

announcement_types =(
    (0,'General'),
    (1,'Food'),
    (2,'Camps'),
    (3,'Weather'),
    (4, 'All'),
)

announcement_priorities = [
    ('H', 'High'),
    ('M', 'Medium'),
    ('L', 'Low')]


class Request(models.Model):
    district = models.CharField(
        max_length = 15,
        choices = districts,
        verbose_name='District - ജില്ല'
    )
    location = models.CharField(max_length=500,verbose_name='Location - സ്ഥലം')
    requestee = models.CharField(max_length=100,verbose_name='Requestee - അപേക്ഷകന്‍റെ പേര്')
    requestee_phone = models.CharField(max_length=10,verbose_name='Requestee Phone - അപേക്ഷകന്‍റെ ഫോണ്‍ നമ്പര്‍', validators=[RegexValidator(regex='^[6-9]\d{9}$', message='Please Enter 10 digit mobile number', code='invalid_mobile')])
    latlng = models.CharField(max_length=100, verbose_name='GPS Coordinates - GPS നിർദ്ദേശാങ്കങ്ങൾ ', blank=True)
    latlng_accuracy = models.CharField(max_length=100, verbose_name='GPS Accuracy - GPS കൃത്യത ', blank=True)
    #  If it is enabled no need to consider lat and lng
    is_request_for_others = models.BooleanField(
        verbose_name='Requesting for others - മറ്റൊരാൾക്ക് വേണ്ടി അപേക്ഷിക്കുന്നു  ', default=False,
        help_text="If it is enabled, no need to consider lat and lng")

    needwater = models.BooleanField(verbose_name='Water - വെള്ളം')
    needfood = models.BooleanField(verbose_name='Food - ഭക്ഷണം')
    needcloth = models.BooleanField(verbose_name='Clothing - വസ്ത്രം')
    needmed = models.BooleanField(verbose_name='Medicine - മരുന്നുകള്‍')
    needtoilet = models.BooleanField(verbose_name='Toiletries - ശുചീകരണ സാമഗ്രികള്‍ ')
    needkit_util = models.BooleanField(verbose_name='Kitchen utensil - അടുക്കള സാമഗ്രികള്‍')
    needrescue = models.BooleanField(verbose_name='Need rescue - രക്ഷാപ്രവർത്തനം ആവശ്യമുണ്ട്')

    detailwater = models.CharField(max_length=250, verbose_name='Details for required water - ആവശ്യമായ വെള്ളത്തിന്‍റെ വിവരങ്ങള്‍', blank=True)
    detailfood = models.CharField(max_length=250, verbose_name='Details for required food - ആവശ്യമായ ഭക്ഷണത്തിന്‍റെ വിവരങ്ങള്‍', blank=True)
    detailcloth = models.CharField(max_length=250, verbose_name='Details for required clothing - ആവശ്യമായ വസ്ത്രത്തിന്‍റെ വിവരങ്ങള്‍', blank=True)
    detailmed = models.CharField(max_length=250, verbose_name='Details for required medicine - ആവശ്യമായ മരുന്നിന്‍റെ  വിവരങ്ങള്‍', blank=True)
    detailtoilet = models.CharField(max_length=250, verbose_name='Details for required toiletries - ആവശ്യമായ  ശുചീകരണ സാമഗ്രികള്‍', blank=True)
    detailkit_util = models.CharField(max_length=250, verbose_name='Details for required kitchen utensil - ആവശ്യമായ അടുക്കള സാമഗ്രികള്‍', blank=True)
    detailrescue = models.CharField(max_length=250, verbose_name='Details for rescue action - രക്ഷാപ്രവർത്തനം വിവരങ്ങള്', blank=True)

    needothers = models.CharField(max_length=500, verbose_name="Other needs - മറ്റു ആവശ്യങ്ങള്‍", blank=True)
    status = models.CharField(
        max_length = 10,
        choices = status_types,
        default = 'new'
    )
    supply_details = models.CharField(max_length=100, blank=True)
    dateadded = models.DateTimeField(auto_now_add=True)

    def summarise(self):
        out = ""
        if(self.needwater):
            out += "Water Requirements :\n {}".format(self.detailwater)
        if(self.needfood):
            out += "\nFood Requirements :\n {}".format(self.detailfood)
        if(self.needcloth):
            out += "\nCloth Requirements :\n {}".format(self.detailcloth)
        if(self.needmed):
            out += "\nMedicine Requirements :\n {}".format(self.detailmed)
        if(self.needtoilet):
            out += "\nToilet Requirements :\n {}".format(self.detailtoilet)
        if(self.needkit_util):
            out += "\nKit Requirements :\n {}".format(self.detailkit_util)
        if(len(self.needothers.strip()) != 0):
            out += "\nOther Needs :\n {}".format(self.needothers)
        return out

    class Meta:
        verbose_name = 'Rescue: Request'
        verbose_name_plural = 'Rescue:Requests'

    def __str__(self):
        return self.get_district_display() + ' ' + self.location

class Volunteer(models.Model):
    district = models.CharField(
        max_length = 15,
        choices = districts,
        verbose_name="District - ജില്ല"
    )
    name = models.CharField(max_length=100, verbose_name="Name - പേര്")
    phone = models.CharField(max_length=10, verbose_name="Phone - ഫോണ്‍ നമ്പര്‍", validators=[RegexValidator(regex='^[6-9]\d{9}$', message='Please Enter 10 digit mobile number', code='invalid_mobile')])
    organisation = models.CharField(max_length=250, verbose_name="Organization (സംഘടന) / Institution")
    address = models.TextField(verbose_name="Address - വിലാസം")
    area = models.CharField(
        max_length = 15,
        choices = vol_categories,
        verbose_name = "Area of volunteering - സന്നദ്ധസേവനം"
    )
    is_spoc = models.BooleanField(default=False, verbose_name="Is point of contact")
    joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Volunteer: Individual'
        verbose_name_plural = 'Volunteers: Individuals'

    def __str__(self):
        return self.name


class NGO(models.Model):
    district = models.CharField(
        max_length = 15,
        choices = districts,
    )
    organisation = models.CharField(max_length=250, verbose_name="Name of Organization (സംഘടനയുടെ പേര്)")
    organisation_type = models.CharField(max_length=250, verbose_name="Type of Organization")
    organisation_address = models.TextField(default='', verbose_name="Address of Organization")
    name = models.CharField(max_length=100, verbose_name="Contact Person")
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone = models.CharField(validators=[phone_regex], max_length=17, blank=True) # validators should be a list
    description = models.TextField(verbose_name="About Organisation")
    area = models.TextField(
        verbose_name = "Area of volunteering"
    )
    location = models.CharField(
        max_length=500,
        verbose_name="Preferred Location to Volunteer"
    )
    is_spoc = models.BooleanField(default=False, verbose_name="Is point of contact")
    joined = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Volunteer: NGO'
        verbose_name_plural = 'Volunteers: NGOs'

    def __str__(self):
        return self.name


class Contributor(models.Model):
    district = models.CharField(
        max_length = 15,
        choices = districts,
        verbose_name="District - ജില്ല"
    )
    name = models.CharField(max_length=100, verbose_name="Name - പേര്")
    phone = models.CharField(max_length=10, verbose_name="Phone - ഫോണ്‍ നമ്പര്‍", validators=[RegexValidator(regex='^[6-9]\d{9}$', message='Please Enter 10 digit mobile number', code='invalid_mobile')])
    address = models.TextField(verbose_name="Address - വിലാസം")
    commodities = models.TextField(verbose_name="What you can contribute. ( സംഭാവന ചെയ്യാന്‍ ഉദ്ദേശിക്കുന്ന സാധനങ്ങള്‍ ) -- Eg: Shirts, torches etc ")
    status = models.CharField(
        max_length = 10,
        choices = contrib_status_types,
        default = 'new'
    )

    class Meta:
        verbose_name = 'Contributor: Donation'
        verbose_name_plural = 'Contributors: Donations'

    def __str__(self):
        return self.name + ' ' + self.get_district_display()


class DistrictManager(models.Model):
    district = models.CharField(
        max_length = 15,
        choices = districts,
        verbose_name="District - ജില്ല"
    )
    name = models.CharField(max_length=100, verbose_name="Name - പേര്")
    phone = models.CharField(max_length=11, verbose_name="Phone - ഫോണ്‍ നമ്പര്‍")
    email = models.CharField(max_length=100, verbose_name="Email - ഇമെയിൽ")

    class Meta:
        verbose_name = 'District: Manager'
        verbose_name_plural = 'District: Managers'

    def __str__(self):
        return self.name + ' ' + self.get_district_display()

class DistrictNeed(models.Model):
    district = models.CharField(
        max_length = 15,
        choices = districts,
    )
    needs = models.TextField(verbose_name="Items required")
    cnandpts = models.TextField(verbose_name="Contacts and collection points") #contacts and collection points

    class Meta:
        verbose_name = 'District: Need'
        verbose_name_plural = 'District: Needs'

    def __str__(self):
        return self.get_district_display()


class DistrictCollection(models.Model):

mainapp/templates/mainapp/aboutieee.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<div class="row text-center static-page-box">
    <h1 class="text-center">About IEEE</h1>
    <p style="font-size:1.7rem;">IEEE– Institute of Electrical and Electronics Engineers, is the world’s largest technical professional society, is continuously promoting the development and application of technology and allied sciences for the benefit of humanity and for the advancement of the profession. Formally started in 1963, IEEE now has 430,000 members spanning across 165 countries of the globe. IEEE fosters the development of standards and advancement of technology for the benifit of humanity.</p>
    <p style="font-size:1.7rem;">
        IEEE Kerala Section, one of the 11 Sections of IEEE in India was founded by the technology giant of Kerala, Late KPP Nambiar in 1983. Several innovations from IEEE Kerala Section in organizing activities for students as well as professionals have been appreciated and replicated by the global IEEE community. Winner of MGA Large Section Award in 2015 and Region 10 (Asia Pacific) Outstanding Large Section Award in 2004, 2009 and 2015, IEEE Kerala Section has been organizing high quality, high impact technical events and humanitarian projects. Please visit our website https://ieeekerala.org/ for more details about the activities of IEEE Kerala section.</p>
</div>
{% endblock %}

mainapp/templates/mainapp/add_person.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{% block content %}  
  <div class="text-right">
    <a href="/coordinator_home">Coordinator Home</a> | 
    <a href="/logout">Logout</a>
  </div>

  <h3 class="text-center">
      Person Registration | 
      വ്യക്തിയെ രജിസ്റ്റർ ചെയ്യുക      
  </h3>

  <div class="text-center text-danger">
      {% if messages %}
        {% for message in messages %}
          <h3>{{ message }}</h3>
        {% endfor %}
      {% endif %}
  </div>

  <form method="post"  class="simple-form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-success">
    Submit {% bootstrap_icon "chevron-right" %}
    </button>
    {% endbuttons %}

    <p class="text-center">
        Please enter all available information. This can help relatives find them if required. <br>
        ബന്ധുക്കൾക്ക് ഇവരെ കണ്ടെത്തുന്നതിന് ഇത് സഹായിക്കും
    </p>
  </form> 

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script>
  $('#id_gender_0').parents('.radio').hide();
  $('#id_gender > .radio').removeClass('radio').addClass('radio-inline');
  $('#id_camped_at').attr('readonly', true);
  </script>

{% endblock %}

mainapp/templates/mainapp/camp_requirements_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

{% block css %}
<style>
.long-col {
  min-width: 250px;
}
</style>

{% endblock %}
<div class="text-center">
  <h3>Camp details</h3>
</div>

<form action="" method="get">
    {{ filter.form.as_p }}
    <button class="btn btn-default" type="submit">Show Relief Camps</button>
</form>
<div class="">
  <table class="table">
    <tr>
      <th>Camp Name</th>
      <th>District</th>
      <th>Taluk</th>
      <th>Village</th>
      <th>Contacts</th>
      <th>Total People</th>
      <th>Total Males</th>
      <th>Total Females</th>
      <th>Total Infants</th>
      <th>Food Requirements</th>
      <th>Clothing Requirements</th>
      <th>Sanitary Requirements</th>
      <th>Medical Requirements</th>
      <th>Other Requirements</th>
    </tr>
  {% for item in data %}
    <tr valign="top">
      <td><strong>{{item.name}}</strong></td>
      <td>
        {{item.get_district_display}}
      </td>
      <td>
        {{item.taluk}}
      </td>
      <td>
        {{item.village}}
      </td>
      <td>
        {{item.contacts|linebreaks}}
      </td>
      <td>
        {{item.total_people}}
      </td>
      <td>
        {{item.total_males}}
      </td>
      <td>
        {{item.total_females}}
      </td>
      <td>
        {{item.total_infants}}
      </td>
      <td class="long-col">
        {{item.food_req|linebreaks}}
      </td>
      <td class="long-col">
        {{item.clothing_req|linebreaks}}
      </td>
      <td class="long-col">
        {{item.sanitary_req|linebreaks}}
      </td>
      <td class="long-col">
        {{item.medical_req|linebreaks}}
      </td>
      <td class="long-col">
        {{item.other_req|linebreaks}}
      </td>
    </tr>
    {% endfor %}
  </table>

  {% if data.paginator.num_pages > 1 %}
  <div class="pagination" >
    <span class="step-links">
        {% if data.has_previous %}
            <a href="?page=1&name__icontains={{ request.GET.name__icontains }}&district={{ request.GET.district }}">&laquo; first</a>
            <a href="?page={{data.previous_page_number}}&name__icontains={{ request.GET.name__icontains }}&district={{ request.GET.district }}">previous</a>
        {% endif %}
  
        {% for i in data.paginator.page_range %}
        {% if data.number == i %}
          <a class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></a>
        {% else %}
          <a href="?page={{i}}&name__icontains={{ request.GET.name__icontains }}&district={{ request.GET.district }}">{{ i }}</a>
        {% endif %}
        {% endfor %}
  
        {% if data.has_next %}
            <a href="?page={{ data.next_page_number }}&name__icontains={{ request.GET.name__icontains }}&district={{ request.GET.district }}">next</a>
            <a href="?page={{ data.paginator.num_pages }}&name__icontains={{ request.GET.name__icontains }}&district={{ request.GET.district }}">last &raquo;</a>
        {% endif %}
    </span>
  </div>
  {% endif %}


</div>
{% endblock %}

mainapp/templates/mainapp/contrib_success.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

<h3 align="center">Our volunteer will contact you soon for collection</h3>
<h3 align="center">ഞങ്ങളുടെ വോളന്റീയർ താങ്കളുമായി ബന്ധപ്പെടുന്നതായിരിക്കും</h3>

{% endblock %}

mainapp/templates/mainapp/contributor_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

<h1 class="text-center">To Contribute</h1>
<h2 class="text-center">സംഭാവന നല്‍കാന്‍</h2>
  <form method="post">
    <b class="text-center"> You can also contribute to Chief Minister's Fund:<br>
      മുഖ്യമന്തിയുടെ ദുരിതാശ്വാസ നിധിയിലേക്ക് സംഭാവന ചെയ്യാം<br/><br>
      <table class="table">
        <tr>
          <td>Account number</td> <td>67319948232</td>
        </tr>
        <tr>
          <td>Name on Account</td> <td>Chief Minister's Distress Relief Fund</td>
        </tr>
        <tr>
          <td>Account Type</td> <td>Savings</td>
        </tr>
        <tr>
          <td>Bank</td> <td>SBI</td>
        </tr>
        <tr>
          <td>Branch</td> <td>City Branch, TVM</td>
        </tr>
        <tr>
          <td>IFS Code</td> <td>SBIN0070028</td>
        </tr>
        <tr>
          <td>SWIFT Code</td> <td>SBININBBT08</td>
        </tr>
      </table>
      <a href="https://donation.cmdrf.kerala.gov.in/">Donate to Chief Minister's Fund Online</a>
    </b><br><br>
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">
  {% bootstrap_icon "star" %} Submit
  </button>
  {% endbuttons %}
  </form>
<script>
    window.onload = function() {
        $("#id_phone").attr('type', 'number');
    }
</script>
{% endblock %}

mainapp/templates/mainapp/coordinator_home.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}


<div class="text-right">
    <a href="/find_people">Search People</a> | 
    <a href="/logout">Logout</a>
</div>

<h3>
  Relief Camp Coordinator | ദുരിതാശ്വാസ ക്യാമ്പ് കോർഡിനേറ്റർ
</h3>

<hr>

<div class="text-center text-danger">
    {% if messages %}
      {% for message in messages %}
        <h4>{{ message }}</h4>
      {% endfor %}
    {% endif %}
</div>

<form action="" method="get">
    {{ filter.form.as_p }}
    <button class="btn btn-default" type="submit"> Show Camps {% bootstrap_icon "chevron-right" %}</button>
</form>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Name</th>
            <th>District</th>
            <th>Taluk/Village</th>
            <th>Registration Count</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for item in data %}
        <tr>
            <td><strong>{{ item.name }}</strong></td>
            <td>{{ item.get_district_display }}</td>
            <td>{{ item.taluk }}<br>{{ item.village }}</td>
            <td>{{ item.count }}</td>
            <td>
                <div class="btn-group">
                    <a href="/camp/{{ item.id  }}/add_person" class="btn btn-default">
                        {% bootstrap_icon "user" %}  Register People
                    </a>
                    <a href="/camp/{{ item.id  }}/requirements" class="btn btn-default">
                        {% bootstrap_icon "pencil" %} Requirements
                    </a>
                     <a href="/camp/{{ item.id  }}/details" class="btn btn-default">
                        {% bootstrap_icon "pencil" %} Camp Details
                    </a>
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% if data.paginator.num_pages > 1 %}
<div class="pagination" >
  <span class="step-links">
      {% if data.has_previous %}
          <a href="?page=1&name__icontains={{ request.GET.name__icontains }}&district={{ request.GET.district }}">&laquo; first</a>
          <a href="?page={{data.previous_page_number}}&name__icontains={{ request.GET.name__icontains }}&district={{ request.GET.district }}">previous</a>
      {% endif %}

      {% for i in data.paginator.page_range %}
      {% if data.number == i %}
        <a class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></a>
      {% else %}
        <a href="?page={{i}}&name__icontains={{ request.GET.name__icontains }}&district={{ request.GET.district }}">{{ i }}</a>
      {% endif %}
      {% endfor %}

      {% if data.has_next %}
          <a href="?page={{ data.next_page_number }}&name__icontains={{ request.GET.name__icontains }}&district={{ request.GET.district }}">next</a>
          <a href="?page={{ data.paginator.num_pages }}&name__icontains={{ request.GET.name__icontains }}&district={{ request.GET.district }}">last &raquo;</a>
      {% endif %}
  </span>
</div>
{% endif %}

{% endblock %}

mainapp/templates/mainapp/disclaimer.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<div class="row text-center static-page-box">
    <h1 class="text-center">Disclaimer</h1>
    <p style="font-size:1.7rem;">This portal has been developed for effective collaboration between various stakeholders such as citizen, Government authorities, various NGOs and volunteers. IEEE makes no representation regarding the completeness, accuracy of any information and data contained on this portal or that such information and data will be error-free. Stakeholders are trying to make their best effort to support, any information received through the portal the requests received through this portal doesn’t warrant any commitment on the services. By using this site you acknowledge that you have read and agree to this</p>
</div>
{% endblock %}

mainapp/templates/mainapp/districtmanager_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<h1 class="text-center">Contact Info</h1>
<h2 class="text-center">ഞങ്ങളുമായി ബന്ധപ്പെടാന്‍</h2>
<p class="text-center">
  Volunteers are available across Kerala. Contact the <u>District level point of contacts</u> for any help. <br/>
  സഹായത്തിനായി വൊളന്‍റീയര്‍മാര്‍ തയ്യാറാണ്. സഹായം ആവശ്യമെങ്കില്‍ ഒരോ ജില്ലയിലെയും നിയോഗിക്കപെട്ട ഉദ്യോഗസ്ഥരുമായി ബന്ധപ്പെടാം
</p>
<form id="find-contact-form" action="" method="get">
       {{ filter.form.as_p }}
 </form>
 <div class="table-responsive">
  <table class="table">
    <tr>
      <th>Name - പേര്</th>
      <th>Phone - ഫോൺ</th>
      <th>Other Contact - മറ്റ് കോൺടാക്റ്റ്</th>
    </tr>
    {% for req in filter.qs %}
        <tr>
          <td>{{ req.name }}</td>
          <td><a href="tel:{{ req.phone }}">{{ req.phone }}</a></td>          <td>{{ req.email }}</td>
        </tr>
    {% endfor %}
  </table>
</div>
<script>
  window.onload = function() {
    $("#id_district").change(() => {
      $("#find-contact-form").submit();
    })
  }

</script>
{% endblock %}